/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const HomeworkItem = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
});
export const Lesson = IDL.Record({
  'day' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'grade' : IDL.Nat,
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'subject' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'grade' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'voicePersona' : IDL.Text,
  'grade' : IDL.Nat,
});
export const QuizAttempt = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Int,
  'questions' : IDL.Vec(QuizQuestion),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHomework' : IDL.Func([HomeworkItem], [], []),
  'addLesson' : IDL.Func([Lesson], [], []),
  'addQuizQuestion' : IDL.Func([QuizQuestion], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAudio' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedLessons' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getHomework' : IDL.Func([], [IDL.Vec(HomeworkItem)], ['query']),
  'getLesson' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Opt(Lesson)],
      ['query'],
    ),
  'getLessonTitles' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getProgressStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'completedQuizzes' : IDL.Nat,
          'completedLessons' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getQuestions' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(QuizQuestion)],
      ['query'],
    ),
  'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markHomeworkDone' : IDL.Func([IDL.Text], [], []),
  'markLessonCompleted' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAttempt' : IDL.Func(
      [IDL.Vec(QuizQuestion), IDL.Vec(IDL.Nat)],
      [IDL.Int],
      [],
    ),
  'uploadAudio' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const HomeworkItem = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'day' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'grade' : IDL.Nat,
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'subject' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'grade' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'voicePersona' : IDL.Text,
    'grade' : IDL.Nat,
  });
  const QuizAttempt = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Int,
    'questions' : IDL.Vec(QuizQuestion),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHomework' : IDL.Func([HomeworkItem], [], []),
    'addLesson' : IDL.Func([Lesson], [], []),
    'addQuizQuestion' : IDL.Func([QuizQuestion], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAudio' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedLessons' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getHomework' : IDL.Func([], [IDL.Vec(HomeworkItem)], ['query']),
    'getLesson' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Opt(Lesson)],
        ['query'],
      ),
    'getLessonTitles' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getProgressStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'completedQuizzes' : IDL.Nat,
            'completedLessons' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getQuestions' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getQuizHistory' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markHomeworkDone' : IDL.Func([IDL.Text], [], []),
    'markLessonCompleted' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAttempt' : IDL.Func(
        [IDL.Vec(QuizQuestion), IDL.Vec(IDL.Nat)],
        [IDL.Int],
        [],
      ),
    'uploadAudio' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };